project:
  type: website
  output-dir: docs
  
exclude:
  - scripts/*

website:
  title: "Jacob Perez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: thesis.qmd
        text: BIRCH in tidyclust
      - href: posts.qmd
        text: STAT 541 Portfolio

format:
  html:
    theme: 
      light: sandstone
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

