project:
  type: website
  output-dir: docs
  
exclude:
  - scripts/*

website:
  title: "Jacob Perez"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - posts.qmd
      - href: resources.qmd
        text: Resources

format:
  html:
    theme: 
      light: sandstone
      dark: superhero
    css: styles.css
    toc: true
    page-layout: full

editor: visual

