---
title: "About"
---

Welcome to my personal portfolio! This website is a hub dedicated to showcasing some my journey and passion for data science and analytics. Over the past 5 years I have been able to learn so much about statistics and data science as a field. Through this learning I have seen just how powerful it is to be able to turn raw data into actionable insights. 

Hopefully here on this website you'll find a collection of projects aimed at making those actionable insights. I have applied a range of skills including data visualization (R, `ggplot2`, Shiny), statistical modeling, data cleaning, and API integration. Each project reflects a different skill and has shaped my path towards data science in many ways. 

Beyond the code and numbers, I love to think strategically about sports analysis and board games. I believe both these hobbies complement my analytical work very well and probably annoy my friends at times with how I treat them. 

Whether you're here to browse my work or take inspiration, I invite you to explore. Feel free to connect if you'd like to discuss anything!
